### PR TITLE
Implemented Introsort

### PR DESCRIPTION
**Pull request by xiroV**
Implementation of the _GNU Standard C++ library_ variation of IntroSort:

First QuickSort-like partitioning to a maximum depth of 2*log(n), where n is the number of elements, followed by an InsertionSort.

### CODE REVIEW

**Comment by xiroV** [comment]
Sorry about the odd commits.. I've probably done something wrong there.

**Comment by Eckankar** [comment]
Thank you!

I just noticed that you're Danish, too. Cool stuff; thanks for the commits!

**Comment by xiroV** [comment]
No problem! Sorting algorithms are fun to implement! :) And yea, I'm from Odense.

**Comment by Eckankar** [comment]
Indeed. And fun to watch play out.

Fellow Dane, then. KU grad. :) You should come say hi on IRC sometime; #diku on freenode.

**Comment by xiroV** [comment]
Sure, I'll be there today :) Same nick as here.

**Pull request merged**
