### PR TITLE
Added Jsort.py

### LINKED ISSUE #7: Implement JSort
https://xlinux.nist.gov/dads/HTML/JSort.html

http://home.westman.wave.ca/~rhenry/sort/src/JSortAlgorithm.java

### PR DESCRIPTION
**Pull request by divyanshu-talwar**
Fixes #7 
JSort Working

### CODE REVIEW

**Comment by divyanshu-talwar** [comment]
Hey! do you wish to implement the SiftSort Algorithm mentioned in your TODO?

**Comment by Eckankar** [comment]
@divyanshu-talwar Go right ahead.

**Comment by divyanshu-talwar** [comment]
Okay
Also, I fixed my error of not pulling from your repository before creating a PR.
Sorry about that.

**Comment by Eckankar** [comment]
@divyanshu-talwar I will take a look at your branch later. Thanks! :)

**Comment by Eckankar** [comment]
Thanks!

**Pull request merged**
